create table datos (
	socio_id INT,
	nombre_socio VARCHAR(50),
	tipo_suscripcion VARCHAR(10),
	fecha_acceso DATE,
	hora_entrada VARCHAR(50),
	duracion_minutos INT,
	zona_actividad VARCHAR(10)
);
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (1, 'Natal', 'Platinum', '2025-11-14', '4:05 PM', 77, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (2, 'Layney', 'Gold', '2025-09-16', '8:05 AM', 85, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (3, 'Atlante', 'Basic', '2025-03-02', '6:07 PM', 117, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (4, 'Pearla', 'Gold', '2025-03-05', '10:53 AM', 39, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (5, 'Mitchel', 'Basic', '2025-12-02', '8:05 PM', 84, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (6, 'Hobart', 'Gold', '2025-02-17', '3:04 PM', 37, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (7, 'Colas', 'Platinum', '2025-05-29', '7:31 AM', 71, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (8, 'Massimiliano', 'Platinum', '2024-12-19', '9:01 PM', 57, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (9, 'Diane-marie', 'Basic', '2025-03-07', '10:09 AM', 83, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (10, 'Madalena', 'Platinum', '2024-12-30', '6:44 PM', 58, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (11, 'Minne', 'Platinum', '2025-08-24', '2:21 PM', 119, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (12, 'Broderick', 'Platinum', '2025-06-21', '5:33 PM', 51, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (13, 'Anjanette', 'Platinum', '2025-05-19', '1:53 PM', 64, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (14, 'Wendell', 'Platinum', '2025-10-03', '7:36 AM', 35, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (15, 'Nealson', 'Basic', '2025-09-01', '8:41 PM', 70, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (16, 'Devonne', 'Platinum', '2025-05-20', '1:50 PM', 85, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (17, 'Kiersten', 'Basic', '2025-02-02', '3:00 PM', 43, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (18, 'Nickie', 'Basic', '2025-10-02', '8:16 AM', 59, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (19, 'Jewell', 'Gold', '2025-08-05', '9:52 AM', 118, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (20, 'Panchito', 'Gold', '2025-08-06', '4:28 PM', 47, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (21, 'Loutitia', 'Gold', '2025-10-15', '5:16 PM', 94, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (22, 'Katina', 'Platinum', '2025-04-05', '11:58 AM', 120, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (23, 'Carlos', 'Gold', '2025-12-05', '1:20 PM', 31, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (24, 'Leicester', 'Platinum', '2025-03-09', '4:35 PM', 91, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (25, 'Corrie', 'Gold', '2025-09-26', '8:03 AM', 106, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (26, 'Lucho', 'Gold', '2025-07-19', '5:55 PM', 88, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (27, 'Lenore', 'Basic', '2025-05-31', '8:52 PM', 111, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (28, 'Lira', 'Platinum', '2025-05-19', '7:49 PM', 115, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (29, 'Sly', 'Platinum', '2025-01-02', '9:05 PM', 70, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (30, 'Sandye', 'Basic', '2025-11-30', '1:50 PM', 39, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (31, 'Shurlocke', 'Platinum', '2025-08-20', '9:01 PM', 50, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (32, 'Evita', 'Platinum', '2025-08-25', '5:49 PM', 92, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (33, 'Stacie', 'Basic', '2025-06-20', '11:38 AM', 105, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (34, 'Kare', 'Gold', '2024-12-25', '3:19 PM', 69, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (35, 'Willamina', 'Gold', '2025-04-01', '9:07 AM', 112, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (36, 'Trix', 'Basic', '2025-06-21', '11:43 AM', 71, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (37, 'Osbourne', 'Gold', '2025-03-23', '11:13 AM', 114, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (38, 'Janean', 'Basic', '2025-11-21', '5:40 PM', 38, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (39, 'Paulita', 'Basic', '2025-02-06', '8:03 PM', 78, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (40, 'Kellina', 'Basic', '2025-08-03', '9:07 PM', 96, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (41, 'Rhody', 'Gold', '2025-03-17', '8:05 AM', 85, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (42, 'Estelle', 'Basic', '2025-07-26', '9:28 PM', 82, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (43, 'Peta', 'Gold', '2025-07-13', '5:53 PM', 73, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (44, 'Gleda', 'Platinum', '2025-05-04', '2:20 PM', 86, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (45, 'Nicky', 'Platinum', '2025-10-31', '11:33 AM', 57, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (46, 'Jo-ann', 'Platinum', '2025-10-08', '1:25 PM', 73, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (47, 'Tymon', 'Gold', '2025-07-26', '3:58 PM', 70, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (48, 'Kenon', 'Basic', '2025-04-26', '4:58 PM', 65, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (49, 'Morgan', 'Gold', '2025-11-26', '3:12 PM', 50, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (50, 'Viviyan', 'Basic', '2025-03-16', '4:19 PM', 64, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (51, 'Payton', 'Platinum', '2025-03-17', '11:27 AM', 50, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (52, 'Prentice', 'Gold', '2025-06-13', '6:03 PM', 39, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (53, 'Ara', 'Gold', '2025-08-25', '5:51 PM', 42, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (54, 'Rosana', 'Platinum', '2024-12-18', '1:47 PM', 68, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (55, 'Stanley', 'Basic', '2025-08-08', '3:55 PM', 66, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (56, 'Adora', 'Gold', '2025-08-27', '9:08 AM', 99, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (57, 'Ash', 'Platinum', '2025-05-25', '8:53 PM', 32, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (58, 'Sallyanne', 'Basic', '2025-03-16', '9:54 AM', 91, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (59, 'Gregorio', 'Gold', '2025-04-30', '12:46 PM', 120, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (60, 'Kenton', 'Gold', '2025-08-09', '8:22 AM', 54, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (61, 'Tarah', 'Platinum', '2025-10-16', '3:03 PM', 115, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (62, 'Mirna', 'Gold', '2025-12-04', '10:09 AM', 68, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (63, 'Adelaide', 'Platinum', '2025-04-01', '5:29 PM', 77, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (64, 'Clemmie', 'Platinum', '2025-03-22', '9:59 AM', 57, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (65, 'Torrence', 'Platinum', '2024-12-24', '7:47 AM', 46, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (66, 'Dione', 'Gold', '2025-04-08', '12:21 PM', 62, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (67, 'Jereme', 'Gold', '2025-05-18', '5:16 PM', 44, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (68, 'Marlo', 'Platinum', '2025-01-02', '11:26 AM', 90, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (69, 'Katharine', 'Basic', '2024-12-22', '10:52 AM', 96, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (70, 'Barton', 'Platinum', '2025-06-05', '5:47 PM', 67, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (71, 'Axe', 'Platinum', '2025-01-31', '8:07 PM', 107, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (72, 'Livvy', 'Platinum', '2025-12-03', '11:55 AM', 33, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (73, 'Reinaldo', 'Basic', '2025-10-03', '5:01 PM', 33, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (74, 'Anneliese', 'Platinum', '2025-06-23', '5:37 PM', 64, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (75, 'Wyatan', 'Platinum', '2025-11-24', '3:26 PM', 100, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (76, 'Terrence', 'Basic', '2025-02-27', '6:42 PM', 74, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (77, 'Kort', 'Gold', '2025-05-23', '2:21 PM', 55, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (78, 'Patty', 'Basic', '2025-02-11', '6:45 PM', 66, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (79, 'Lucie', 'Gold', '2025-09-25', '4:32 PM', 68, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (80, 'Uri', 'Platinum', '2025-12-08', '2:06 PM', 97, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (81, 'Delmer', 'Gold', '2025-10-06', '3:43 PM', 35, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (82, 'Valentine', 'Platinum', '2025-05-16', '4:27 PM', 109, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (83, 'Lincoln', 'Basic', '2025-08-11', '9:04 AM', 70, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (84, 'Anselm', 'Platinum', '2025-03-31', '11:00 AM', 73, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (85, 'Roxana', 'Platinum', '2025-03-13', '7:51 AM', 63, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (86, 'Dido', 'Platinum', '2025-02-11', '11:44 AM', 73, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (87, 'Robin', 'Platinum', '2025-12-09', '8:19 AM', 53, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (88, 'Dorian', 'Basic', '2025-05-14', '5:32 PM', 99, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (89, 'Kinny', 'Basic', '2025-08-08', '10:24 AM', 93, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (90, 'Carroll', 'Platinum', '2025-09-13', '2:53 PM', 78, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (91, 'Bertram', 'Basic', '2025-03-31', '6:14 PM', 113, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (92, 'Corabelle', 'Basic', '2025-05-09', '6:51 PM', 69, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (93, 'Dana', 'Basic', '2025-02-15', '6:24 PM', 104, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (94, 'Kendre', 'Platinum', '2025-04-29', '3:33 PM', 108, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (95, 'Anica', 'Gold', '2025-05-12', '6:12 PM', 118, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (96, 'Rollie', 'Platinum', '2025-11-21', '8:49 AM', 52, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (97, 'Gretal', 'Platinum', '2025-11-17', '1:08 PM', 77, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (98, 'Alexandra', 'Platinum', '2025-04-21', '3:49 PM', 72, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (99, 'Odelle', 'Gold', '2025-08-08', '1:54 PM', 86, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (100, 'Nicolette', 'Platinum', '2025-03-27', '10:40 AM', 68, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (101, 'Lira', 'Basic', '2025-07-22', '7:30 PM', 32, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (102, 'Deb', 'Platinum', '2025-01-27', '4:16 PM', 120, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (103, 'Lyssa', 'Gold', '2025-09-14', '3:02 PM', 111, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (104, 'Ellie', 'Basic', '2025-08-09', '11:38 AM', 72, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (105, 'Brittan', 'Basic', '2025-02-27', '10:03 AM', 70, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (106, 'Glory', 'Basic', '2025-07-10', '9:15 PM', 32, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (107, 'Caspar', 'Basic', '2025-11-06', '11:21 AM', 55, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (108, 'Vite', 'Platinum', '2025-10-11', '6:04 PM', 54, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (109, 'Devonne', 'Basic', '2025-11-08', '12:01 PM', 56, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (110, 'Perle', 'Platinum', '2025-10-10', '5:51 PM', 71, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (111, 'Florian', 'Platinum', '2025-11-20', '8:37 PM', 42, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (112, 'Inna', 'Basic', '2025-11-26', '4:10 PM', 66, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (113, 'Cam', 'Gold', '2025-05-01', '12:07 PM', 30, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (114, 'Bradly', 'Platinum', '2025-07-15', '9:06 AM', 81, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (115, 'Gisela', 'Basic', '2025-06-14', '2:47 PM', 106, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (116, 'Jenn', 'Basic', '2025-12-02', '6:51 PM', 61, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (117, 'Felicle', 'Gold', '2025-08-28', '3:51 PM', 109, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (118, 'Lorelle', 'Gold', '2025-08-05', '5:38 PM', 113, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (119, 'Mandi', 'Platinum', '2025-03-05', '6:59 PM', 95, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (120, 'Patrizius', 'Basic', '2025-05-02', '9:15 AM', 47, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (121, 'Karoly', 'Platinum', '2025-10-10', '6:00 PM', 105, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (122, 'Cassondra', 'Gold', '2025-11-02', '8:52 PM', 104, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (123, 'Fergus', 'Gold', '2025-05-07', '4:46 PM', 114, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (124, 'Gui', 'Gold', '2025-01-22', '8:59 AM', 69, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (125, 'Leonora', 'Platinum', '2025-01-13', '7:27 PM', 43, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (126, 'Osmund', 'Platinum', '2025-08-22', '5:32 PM', 105, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (127, 'Galen', 'Basic', '2025-04-16', '4:09 PM', 89, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (128, 'Stesha', 'Basic', '2025-06-03', '3:42 PM', 58, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (129, 'Palmer', 'Gold', '2025-07-17', '8:25 PM', 99, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (130, 'Saundra', 'Platinum', '2025-07-21', '11:06 AM', 65, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (131, 'Tyson', 'Gold', '2025-03-31', '2:23 PM', 52, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (132, 'Caspar', 'Platinum', '2025-11-04', '6:59 PM', 77, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (133, 'Ethe', 'Basic', '2025-08-04', '9:52 AM', 79, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (134, 'Anna-diane', 'Platinum', '2025-09-24', '10:10 AM', 78, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (135, 'Myrwyn', 'Platinum', '2025-01-23', '6:46 PM', 77, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (136, 'Laurence', 'Gold', '2025-08-09', '5:07 PM', 99, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (137, 'Francisco', 'Basic', '2025-11-21', '10:17 AM', 70, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (138, 'Laetitia', 'Gold', '2025-02-04', '1:32 PM', 58, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (139, 'Abdel', 'Gold', '2025-10-18', '9:26 AM', 65, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (140, 'Anallese', 'Platinum', '2025-01-07', '11:31 AM', 104, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (141, 'Findlay', 'Basic', '2025-02-09', '12:48 PM', 118, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (142, 'Isaak', 'Gold', '2025-05-22', '9:22 PM', 120, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (143, 'Gilles', 'Gold', '2025-10-02', '8:01 AM', 48, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (144, 'Suellen', 'Gold', '2025-01-29', '3:03 PM', 79, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (145, 'Pepi', 'Gold', '2025-09-07', '8:21 AM', 100, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (146, 'Deana', 'Platinum', '2025-11-04', '7:03 PM', 34, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (147, 'Danell', 'Platinum', '2025-02-13', '8:48 AM', 98, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (148, 'Anabella', 'Platinum', '2025-09-12', '7:27 PM', 51, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (149, 'Cedric', 'Platinum', '2025-12-17', '7:49 AM', 38, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (150, 'Ardyth', 'Basic', '2025-03-31', '6:27 PM', 43, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (151, 'Mort', 'Basic', '2025-10-16', '11:38 AM', 117, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (152, 'Jone', 'Basic', '2025-03-17', '4:00 PM', 47, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (153, 'Buck', 'Gold', '2025-11-17', '9:11 AM', 104, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (154, 'Aguste', 'Basic', '2025-10-12', '4:45 PM', 82, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (155, 'Maible', 'Basic', '2025-12-16', '2:31 PM', 89, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (156, 'Micki', 'Gold', '2025-11-27', '4:13 PM', 64, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (157, 'Brodie', 'Platinum', '2025-02-01', '12:51 PM', 45, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (158, 'Marne', 'Basic', '2025-12-15', '5:21 PM', 108, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (159, 'Eolande', 'Basic', '2025-07-27', '6:43 PM', 88, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (160, 'Celestyn', 'Platinum', '2025-05-31', '1:48 PM', 49, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (161, 'Jessie', 'Basic', '2025-03-09', '10:30 AM', 43, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (162, 'Caresa', 'Platinum', '2024-12-23', '9:30 AM', 58, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (163, 'Eadith', 'Platinum', '2025-06-23', '12:46 PM', 111, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (164, 'Nickie', 'Gold', '2025-10-10', '3:03 PM', 53, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (165, 'Judd', 'Gold', '2025-09-14', '4:08 PM', 80, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (166, 'Aryn', 'Gold', '2025-08-04', '3:47 PM', 93, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (167, 'Catherine', 'Basic', '2025-06-28', '10:52 AM', 35, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (168, 'Rutger', 'Platinum', '2025-10-07', '5:18 PM', 98, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (169, 'Isabelita', 'Basic', '2025-11-18', '2:51 PM', 103, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (170, 'Kelly', 'Gold', '2025-11-06', '7:46 PM', 82, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (171, 'Isabel', 'Platinum', '2024-12-21', '12:00 PM', 101, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (172, 'Khalil', 'Basic', '2025-11-24', '8:10 AM', 99, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (173, 'Aundrea', 'Platinum', '2025-01-10', '6:14 PM', 88, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (174, 'Dottie', 'Gold', '2025-07-28', '8:42 PM', 97, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (175, 'Wilie', 'Basic', '2025-06-25', '3:26 PM', 106, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (176, 'Gaylene', 'Platinum', '2025-07-04', '8:37 PM', 35, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (177, 'Maitilde', 'Platinum', '2024-12-26', '8:03 AM', 72, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (178, 'Sherm', 'Platinum', '2025-06-30', '7:37 AM', 64, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (179, 'Keenan', 'Platinum', '2025-08-02', '10:05 AM', 78, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (180, 'Caitrin', 'Gold', '2025-02-01', '8:06 PM', 73, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (181, 'Kevyn', 'Platinum', '2025-11-03', '6:32 PM', 112, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (182, 'Marylou', 'Gold', '2025-03-18', '9:11 PM', 93, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (183, 'Meade', 'Gold', '2025-05-10', '8:44 PM', 77, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (184, 'Eddy', 'Platinum', '2025-05-22', '2:10 PM', 79, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (185, 'Chantal', 'Platinum', '2025-07-17', '7:48 PM', 113, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (186, 'Tiffanie', 'Gold', '2025-08-20', '9:56 AM', 106, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (187, 'Lenka', 'Basic', '2025-03-03', '11:35 AM', 83, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (188, 'Bertina', 'Basic', '2025-04-09', '2:43 PM', 116, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (189, 'Maurie', 'Basic', '2025-01-07', '7:56 AM', 103, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (190, 'Viviyan', 'Basic', '2025-11-24', '7:49 PM', 61, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (191, 'Iolanthe', 'Basic', '2025-08-10', '11:05 AM', 103, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (192, 'Inglis', 'Basic', '2025-02-05', '7:45 PM', 62, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (193, 'Helen-elizabeth', 'Platinum', '2025-04-13', '12:19 PM', 73, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (194, 'Trudie', 'Gold', '2025-03-04', '2:11 PM', 101, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (195, 'Nil', 'Platinum', '2024-12-20', '3:27 PM', 68, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (196, 'Onfre', 'Platinum', '2025-12-01', '12:40 PM', 113, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (197, 'Bastien', 'Basic', '2025-04-12', '11:35 AM', 76, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (198, 'Merci', 'Basic', '2025-05-21', '5:23 PM', 38, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (199, 'Tan', 'Platinum', '2025-01-12', '5:17 PM', 80, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (200, 'Tracie', 'Platinum', '2025-10-21', '3:43 PM', 106, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (201, 'Nicki', 'Basic', '2025-10-18', '12:53 PM', 71, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (202, 'Gar', 'Basic', '2025-04-11', '10:55 AM', 40, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (203, 'Isahella', 'Basic', '2025-09-04', '7:42 PM', 38, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (204, 'Fidel', 'Basic', '2025-01-08', '7:36 AM', 114, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (205, 'Anastassia', 'Gold', '2025-07-08', '1:11 PM', 61, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (206, 'Tynan', 'Platinum', '2025-05-18', '11:14 AM', 82, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (207, 'Fletch', 'Basic', '2025-01-24', '12:05 PM', 44, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (208, 'Florenza', 'Platinum', '2025-06-30', '10:28 AM', 110, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (209, 'Kelley', 'Gold', '2025-10-01', '11:57 AM', 93, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (210, 'Carolus', 'Platinum', '2025-07-10', '7:57 AM', 113, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (211, 'Pavel', 'Platinum', '2025-08-10', '5:16 PM', 102, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (212, 'Ashil', 'Platinum', '2025-09-18', '7:22 PM', 107, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (213, 'Linell', 'Platinum', '2025-10-17', '3:43 PM', 76, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (214, 'Sherrie', 'Basic', '2025-09-19', '10:04 AM', 41, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (215, 'Minetta', 'Gold', '2025-09-03', '9:03 PM', 56, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (216, 'Englebert', 'Platinum', '2025-10-07', '2:43 PM', 60, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (217, 'Aliza', 'Gold', '2025-06-09', '2:19 PM', 90, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (218, 'Ruthy', 'Basic', '2024-12-24', '9:14 PM', 74, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (219, 'Dara', 'Platinum', '2025-05-16', '7:29 PM', 47, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (220, 'Audra', 'Gold', '2025-11-11', '8:31 AM', 83, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (221, 'Dyana', 'Basic', '2024-12-23', '5:13 PM', 87, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (222, 'Donna', 'Basic', '2025-09-23', '7:45 AM', 82, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (223, 'Reena', 'Gold', '2025-07-08', '9:30 AM', 54, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (224, 'Ophelie', 'Platinum', '2025-01-15', '10:00 AM', 38, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (225, 'Jeni', 'Basic', '2025-01-13', '7:16 PM', 117, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (226, 'Rozalin', 'Platinum', '2025-09-04', '8:26 AM', 67, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (227, 'Kyle', 'Gold', '2025-04-23', '6:54 PM', 85, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (228, 'Scotti', 'Gold', '2024-12-21', '2:45 PM', 120, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (229, 'Briggs', 'Gold', '2025-10-08', '6:01 PM', 90, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (230, 'Rhodie', 'Platinum', '2025-08-14', '5:59 PM', 67, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (231, 'Webster', 'Platinum', '2025-01-23', '9:32 AM', 111, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (232, 'Bobbette', 'Gold', '2025-01-12', '1:57 PM', 119, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (233, 'Lillian', 'Gold', '2025-11-26', '4:41 PM', 97, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (234, 'Karon', 'Gold', '2025-10-15', '2:20 PM', 47, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (235, 'Nahum', 'Gold', '2025-08-28', '11:39 AM', 84, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (236, 'Cherida', 'Platinum', '2025-07-18', '1:40 PM', 97, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (237, 'Maurita', 'Basic', '2025-01-23', '3:14 PM', 72, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (238, 'Mira', 'Gold', '2025-09-06', '8:58 PM', 75, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (239, 'Elspeth', 'Platinum', '2025-02-01', '6:16 PM', 47, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (240, 'Steffane', 'Basic', '2025-03-14', '1:33 PM', 92, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (241, 'Sigismundo', 'Platinum', '2025-11-23', '2:41 PM', 101, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (242, 'Lonnard', 'Basic', '2025-12-11', '3:11 PM', 108, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (243, 'Del', 'Gold', '2025-11-24', '7:39 AM', 114, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (244, 'Patsy', 'Platinum', '2025-08-11', '4:17 PM', 39, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (245, 'Issi', 'Gold', '2025-11-25', '11:56 AM', 76, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (246, 'Erik', 'Gold', '2025-04-27', '12:18 PM', 97, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (247, 'Franz', 'Basic', '2025-08-19', '4:18 PM', 38, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (248, 'Boigie', 'Gold', '2025-10-15', '3:58 PM', 94, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (249, 'Chaddy', 'Gold', '2025-02-22', '5:18 PM', 56, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (250, 'Cecil', 'Gold', '2025-04-04', '10:22 AM', 99, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (251, 'Chucho', 'Gold', '2025-03-29', '7:47 AM', 100, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (252, 'Florella', 'Basic', '2025-11-21', '9:19 AM', 56, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (253, 'Maryanna', 'Basic', '2025-12-11', '1:02 PM', 109, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (254, 'Wilt', 'Basic', '2025-05-03', '10:42 AM', 111, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (255, 'Ondrea', 'Gold', '2025-08-30', '6:28 PM', 36, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (256, 'Arman', 'Basic', '2025-05-28', '10:57 AM', 93, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (257, 'Devora', 'Gold', '2025-12-05', '4:55 PM', 62, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (258, 'Howie', 'Basic', '2025-04-30', '6:35 PM', 50, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (259, 'Danyette', 'Gold', '2025-12-05', '7:34 PM', 40, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (260, 'Eugene', 'Basic', '2025-07-05', '3:32 PM', 44, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (261, 'Pietra', 'Platinum', '2024-12-29', '5:35 PM', 46, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (262, 'Britta', 'Basic', '2025-04-20', '2:37 PM', 65, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (263, 'Madelle', 'Gold', '2025-08-22', '7:20 PM', 82, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (264, 'Tabbi', 'Basic', '2025-03-30', '12:09 PM', 60, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (265, 'Thornie', 'Platinum', '2025-05-01', '9:27 AM', 52, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (266, 'Berthe', 'Gold', '2025-10-30', '1:28 PM', 46, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (267, 'Briant', 'Platinum', '2025-02-10', '10:22 AM', 88, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (268, 'Neely', 'Platinum', '2025-05-08', '11:13 AM', 116, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (269, 'Granthem', 'Gold', '2025-06-04', '9:35 AM', 68, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (270, 'Lancelot', 'Platinum', '2025-06-06', '9:20 AM', 108, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (271, 'Teddy', 'Platinum', '2025-08-23', '7:46 AM', 33, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (272, 'Padriac', 'Platinum', '2025-03-26', '8:56 PM', 55, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (273, 'Calla', 'Platinum', '2025-08-08', '8:53 AM', 107, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (274, 'Janek', 'Gold', '2025-04-14', '5:23 PM', 33, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (275, 'Chico', 'Gold', '2025-09-25', '8:02 AM', 49, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (276, 'Gerick', 'Platinum', '2025-10-11', '8:14 PM', 35, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (277, 'Artie', 'Gold', '2025-06-14', '4:44 PM', 50, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (278, 'Ranice', 'Gold', '2025-12-07', '3:16 PM', 110, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (279, 'Kassandra', 'Basic', '2025-09-28', '10:39 AM', 89, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (280, 'Aubert', 'Gold', '2025-03-21', '11:49 AM', 70, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (281, 'Franciskus', 'Gold', '2025-05-05', '4:16 PM', 115, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (282, 'Karlotta', 'Basic', '2025-11-15', '8:39 PM', 106, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (283, 'Annaliese', 'Platinum', '2025-05-10', '1:48 PM', 37, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (284, 'Emera', 'Gold', '2025-06-28', '9:35 AM', 58, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (285, 'Pearl', 'Gold', '2025-10-07', '7:51 PM', 78, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (286, 'Angel', 'Gold', '2025-04-04', '2:46 PM', 75, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (287, 'Tami', 'Gold', '2025-08-20', '7:51 AM', 107, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (288, 'Verney', 'Platinum', '2025-02-13', '6:31 PM', 96, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (289, 'Rutherford', 'Platinum', '2025-11-06', '1:10 PM', 89, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (290, 'Jemimah', 'Platinum', '2025-06-01', '4:49 PM', 71, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (291, 'Georgia', 'Gold', '2025-05-21', '8:29 PM', 66, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (292, 'Jordanna', 'Platinum', '2025-01-23', '3:49 PM', 58, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (293, 'Keeley', 'Basic', '2025-08-21', '11:07 AM', 61, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (294, 'Harlan', 'Platinum', '2025-10-25', '12:10 PM', 101, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (295, 'Bernard', 'Basic', '2025-06-23', '11:55 AM', 55, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (296, 'Binnie', 'Platinum', '2025-03-10', '1:27 PM', 107, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (297, 'Tobit', 'Gold', '2025-05-28', '3:32 PM', 83, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (298, 'Dicky', 'Gold', '2025-10-17', '5:34 PM', 113, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (299, 'Jeromy', 'Basic', '2025-06-13', '12:37 PM', 67, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (300, 'Keelby', 'Platinum', '2025-05-07', '4:21 PM', 36, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (301, 'Borg', 'Basic', '2025-08-19', '11:52 AM', 65, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (302, 'Dominique', 'Platinum', '2025-01-21', '12:46 PM', 113, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (303, 'Nell', 'Gold', '2025-04-28', '7:46 PM', 40, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (304, 'Law', 'Basic', '2025-06-24', '5:06 PM', 37, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (305, 'Andreas', 'Platinum', '2025-09-20', '2:58 PM', 102, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (306, 'Abran', 'Platinum', '2025-11-30', '4:58 PM', 100, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (307, 'Kiele', 'Platinum', '2025-07-16', '12:29 PM', 46, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (308, 'Shelby', 'Basic', '2025-11-25', '12:51 PM', 85, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (309, 'Elladine', 'Platinum', '2025-06-10', '8:42 AM', 50, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (310, 'Lennard', 'Basic', '2025-11-25', '3:37 PM', 89, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (311, 'Freemon', 'Platinum', '2025-10-01', '7:11 PM', 77, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (312, 'Ruddie', 'Platinum', '2025-05-22', '8:04 PM', 64, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (313, 'Malchy', 'Gold', '2025-11-02', '7:53 PM', 82, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (314, 'Irene', 'Basic', '2025-02-15', '5:56 PM', 97, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (315, 'Hillel', 'Gold', '2025-04-26', '2:29 PM', 33, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (316, 'Ariel', 'Basic', '2025-03-03', '4:50 PM', 101, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (317, 'Alecia', 'Gold', '2025-07-27', '6:53 PM', 38, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (318, 'Celestia', 'Platinum', '2025-02-19', '8:50 PM', 111, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (319, 'Shelly', 'Gold', '2025-10-24', '12:37 PM', 116, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (320, 'Irvin', 'Basic', '2025-07-10', '1:19 PM', 112, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (321, 'Darin', 'Platinum', '2025-02-17', '7:48 AM', 90, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (322, 'Tamarah', 'Gold', '2025-09-17', '11:08 AM', 84, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (323, 'Ali', 'Basic', '2025-05-22', '8:11 PM', 101, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (324, 'Courtnay', 'Basic', '2025-12-08', '1:46 PM', 100, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (325, 'Elias', 'Basic', '2025-05-16', '9:57 AM', 35, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (326, 'Carroll', 'Basic', '2024-12-25', '2:56 PM', 43, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (327, 'Adelina', 'Platinum', '2025-07-26', '11:42 AM', 65, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (328, 'Paulie', 'Basic', '2025-05-13', '10:20 AM', 108, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (329, 'Rosalie', 'Basic', '2025-01-08', '6:55 PM', 32, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (330, 'Major', 'Gold', '2025-03-12', '3:11 PM', 102, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (331, 'Licha', 'Basic', '2025-05-12', '8:25 AM', 84, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (332, 'Sibley', 'Basic', '2025-10-23', '8:51 PM', 56, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (333, 'Reamonn', 'Gold', '2025-11-10', '9:51 AM', 51, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (334, 'Guthrey', 'Gold', '2025-11-26', '9:07 AM', 55, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (335, 'Edin', 'Platinum', '2025-02-26', '7:28 PM', 53, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (336, 'Gayleen', 'Basic', '2025-11-07', '10:10 AM', 57, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (337, 'Shea', 'Basic', '2025-06-04', '7:49 AM', 113, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (338, 'Cassondra', 'Platinum', '2025-05-30', '2:54 PM', 51, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (339, 'Mikey', 'Basic', '2025-11-19', '7:39 PM', 117, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (340, 'Zebadiah', 'Platinum', '2025-05-28', '8:35 AM', 88, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (341, 'Michael', 'Gold', '2025-09-06', '9:13 AM', 77, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (342, 'Bertrand', 'Platinum', '2025-05-10', '1:45 PM', 87, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (343, 'Linnea', 'Gold', '2024-12-19', '1:14 PM', 44, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (344, 'Orsola', 'Basic', '2025-10-13', '6:56 PM', 88, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (345, 'Milly', 'Platinum', '2025-01-04', '8:39 PM', 62, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (346, 'Pavia', 'Platinum', '2025-10-18', '8:25 PM', 105, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (347, 'Shaun', 'Platinum', '2025-10-16', '1:47 PM', 38, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (348, 'Minnnie', 'Platinum', '2025-05-04', '9:09 AM', 54, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (349, 'Lilian', 'Platinum', '2025-11-07', '5:30 PM', 50, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (350, 'Merell', 'Platinum', '2025-11-24', '8:52 PM', 77, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (351, 'Cameron', 'Platinum', '2025-09-13', '10:04 AM', 72, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (352, 'Aloysius', 'Platinum', '2024-12-24', '11:32 AM', 72, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (353, 'Murry', 'Gold', '2025-05-29', '10:49 AM', 30, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (354, 'Kippy', 'Gold', '2025-10-27', '7:22 PM', 98, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (355, 'Claybourne', 'Gold', '2024-12-24', '12:16 PM', 47, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (356, 'Von', 'Gold', '2025-01-01', '1:37 PM', 102, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (357, 'Lanie', 'Gold', '2025-09-16', '8:35 PM', 87, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (358, 'Burg', 'Platinum', '2025-01-24', '10:26 AM', 53, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (359, 'Gill', 'Platinum', '2025-09-27', '12:04 PM', 89, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (360, 'Ogden', 'Gold', '2025-07-19', '11:47 AM', 77, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (361, 'Roselin', 'Basic', '2025-05-29', '7:41 AM', 120, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (362, 'Russell', 'Basic', '2025-05-11', '1:28 PM', 105, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (363, 'Orlando', 'Gold', '2025-02-14', '9:47 AM', 80, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (364, 'Morissa', 'Basic', '2025-12-17', '8:46 PM', 82, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (365, 'Farlee', 'Gold', '2025-06-30', '12:24 PM', 92, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (366, 'Garey', 'Gold', '2025-05-27', '9:27 PM', 114, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (367, 'Nobe', 'Platinum', '2025-05-21', '9:42 AM', 107, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (368, 'Derrick', 'Basic', '2025-11-17', '1:08 PM', 114, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (369, 'Thor', 'Platinum', '2025-01-24', '2:46 PM', 38, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (370, 'Ikey', 'Basic', '2025-11-01', '8:23 AM', 100, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (371, 'Dal', 'Gold', '2024-12-22', '3:46 PM', 103, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (372, 'Flinn', 'Basic', '2025-12-09', '5:06 PM', 34, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (373, 'Claudia', 'Gold', '2025-11-27', '8:50 AM', 61, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (374, 'Lucio', 'Platinum', '2025-11-03', '7:55 PM', 116, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (375, 'Joachim', 'Gold', '2025-05-24', '9:16 AM', 63, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (376, 'Dewey', 'Basic', '2025-03-03', '9:18 AM', 91, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (377, 'Neysa', 'Gold', '2024-12-24', '2:44 PM', 78, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (378, 'Ira', 'Basic', '2025-06-28', '7:46 PM', 64, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (379, 'Reagan', 'Gold', '2025-08-15', '12:38 PM', 84, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (380, 'Leila', 'Gold', '2025-01-10', '8:44 AM', 74, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (381, 'Cyrus', 'Basic', '2025-10-10', '12:49 PM', 59, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (382, 'Kippy', 'Platinum', '2025-07-07', '8:38 PM', 33, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (383, 'Jarred', 'Basic', '2024-12-24', '12:15 PM', 119, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (384, 'Conn', 'Basic', '2025-10-01', '10:16 AM', 63, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (385, 'Babbette', 'Basic', '2025-04-17', '3:31 PM', 78, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (386, 'Napoleon', 'Platinum', '2025-10-16', '5:39 PM', 78, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (387, 'Hillel', 'Platinum', '2025-05-16', '12:47 PM', 81, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (388, 'Calv', 'Gold', '2025-07-14', '2:51 PM', 54, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (389, 'Valida', 'Gold', '2025-07-28', '8:49 PM', 36, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (390, 'Alexandro', 'Basic', '2025-10-10', '9:15 PM', 95, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (391, 'Ninette', 'Platinum', '2025-10-29', '9:15 PM', 115, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (392, 'Grissel', 'Platinum', '2025-04-13', '8:28 AM', 43, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (393, 'Zola', 'Basic', '2025-09-20', '7:58 PM', 117, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (394, 'Demetre', 'Basic', '2025-03-12', '5:48 PM', 50, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (395, 'Hilario', 'Platinum', '2025-07-22', '9:11 AM', 45, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (396, 'Crystal', 'Gold', '2025-01-25', '3:33 PM', 94, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (397, 'Cyndi', 'Platinum', '2025-02-19', '9:23 AM', 90, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (398, 'Sherlock', 'Basic', '2025-07-11', '7:46 AM', 116, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (399, 'Blanca', 'Platinum', '2025-02-28', '5:20 PM', 98, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (400, 'Bayard', 'Gold', '2024-12-27', '7:34 AM', 101, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (401, 'Zaneta', 'Gold', '2025-01-20', '11:14 AM', 39, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (402, 'Sanson', 'Basic', '2025-01-29', '6:46 PM', 98, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (403, 'Mattheus', 'Basic', '2025-10-03', '10:24 AM', 36, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (404, 'Ram', 'Platinum', '2025-11-14', '5:57 PM', 84, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (405, 'Jasper', 'Basic', '2025-07-19', '10:43 AM', 115, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (406, 'Tades', 'Basic', '2025-01-15', '4:34 PM', 70, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (407, 'Candis', 'Platinum', '2025-11-29', '12:47 PM', 72, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (408, 'Tabitha', 'Gold', '2025-03-11', '7:22 PM', 99, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (409, 'Dredi', 'Basic', '2025-07-23', '12:20 PM', 66, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (410, 'Raine', 'Gold', '2025-07-27', '9:08 AM', 103, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (411, 'Abraham', 'Platinum', '2025-02-09', '8:04 AM', 104, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (412, 'Cliff', 'Platinum', '2025-10-02', '1:30 PM', 107, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (413, 'Tarrah', 'Platinum', '2025-02-27', '8:21 PM', 111, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (414, 'Valery', 'Gold', '2025-12-13', '9:22 AM', 50, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (415, 'Ella', 'Basic', '2025-02-10', '12:49 PM', 104, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (416, 'Lesly', 'Basic', '2025-03-07', '8:28 AM', 40, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (417, 'Lulu', 'Gold', '2025-07-17', '8:22 AM', 54, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (418, 'Ashli', 'Basic', '2025-10-11', '5:08 PM', 49, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (419, 'Avrit', 'Gold', '2025-11-14', '7:29 PM', 70, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (420, 'Joyce', 'Platinum', '2025-06-23', '4:52 PM', 98, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (421, 'Bonnibelle', 'Gold', '2025-07-21', '1:52 PM', 85, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (422, 'Ahmed', 'Platinum', '2025-04-03', '2:40 PM', 36, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (423, 'Ynes', 'Gold', '2025-04-17', '8:21 AM', 30, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (424, 'Alysia', 'Basic', '2025-11-06', '4:41 PM', 116, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (425, 'Berta', 'Gold', '2025-04-28', '3:08 PM', 71, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (426, 'Helena', 'Basic', '2025-01-24', '10:55 AM', 63, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (427, 'Felita', 'Platinum', '2025-02-03', '11:32 AM', 84, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (428, 'Wilmer', 'Gold', '2025-07-04', '6:37 PM', 70, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (429, 'Northrup', 'Basic', '2025-09-08', '1:02 PM', 38, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (430, 'Bradley', 'Platinum', '2025-03-15', '8:02 AM', 84, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (431, 'Griz', 'Basic', '2025-10-10', '5:42 PM', 109, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (432, 'Palmer', 'Platinum', '2025-01-22', '10:58 AM', 78, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (433, 'Ignacius', 'Gold', '2025-08-02', '4:11 PM', 92, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (434, 'Hetti', 'Platinum', '2025-02-14', '5:34 PM', 103, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (435, 'Thaddus', 'Gold', '2025-09-19', '8:40 AM', 50, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (436, 'Smith', 'Basic', '2025-10-05', '7:00 PM', 47, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (437, 'Del', 'Gold', '2025-07-19', '9:06 AM', 34, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (438, 'Heriberto', 'Gold', '2025-02-22', '9:30 AM', 63, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (439, 'Ruthy', 'Platinum', '2025-08-10', '1:40 PM', 86, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (440, 'Jemmie', 'Platinum', '2025-06-06', '12:20 PM', 63, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (441, 'Burl', 'Platinum', '2025-04-14', '11:00 AM', 75, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (442, 'Olva', 'Basic', '2025-05-19', '2:54 PM', 116, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (443, 'Angelina', 'Gold', '2025-08-31', '12:05 PM', 68, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (444, 'Larisa', 'Gold', '2025-01-25', '9:56 AM', 83, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (445, 'Maighdiln', 'Basic', '2025-05-27', '4:37 PM', 55, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (446, 'Any', 'Gold', '2025-06-10', '8:01 PM', 116, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (447, 'Steffie', 'Basic', '2025-12-05', '6:54 PM', 64, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (448, 'Boony', 'Basic', '2025-10-10', '5:35 PM', 99, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (449, 'Gayle', 'Basic', '2024-12-21', '8:57 AM', 100, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (450, 'Gwendolyn', 'Platinum', '2025-04-18', '10:19 AM', 37, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (451, 'Misti', 'Basic', '2025-07-03', '10:09 AM', 100, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (452, 'Arluene', 'Platinum', '2024-12-29', '9:12 PM', 111, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (453, 'Aurie', 'Platinum', '2025-11-18', '4:22 PM', 34, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (454, 'Beulah', 'Gold', '2025-05-29', '9:19 PM', 53, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (455, 'Obie', 'Basic', '2025-05-28', '12:55 PM', 77, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (456, 'Baillie', 'Basic', '2025-03-05', '4:04 PM', 75, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (457, 'Penni', 'Platinum', '2025-03-26', '12:20 PM', 74, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (458, 'Barr', 'Platinum', '2025-09-15', '9:48 AM', 71, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (459, 'Emile', 'Gold', '2025-05-12', '1:32 PM', 117, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (460, 'Tessi', 'Platinum', '2025-02-25', '2:39 PM', 80, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (461, 'Doralynn', 'Gold', '2025-07-08', '1:47 PM', 108, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (462, 'Ambrosio', 'Gold', '2025-05-31', '11:46 AM', 87, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (463, 'Deina', 'Basic', '2025-09-08', '8:40 PM', 30, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (464, 'Alice', 'Platinum', '2025-06-26', '5:20 PM', 73, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (465, 'Frankie', 'Basic', '2025-10-20', '5:09 PM', 118, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (466, 'Broderic', 'Basic', '2025-02-02', '8:46 PM', 120, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (467, 'Archaimbaud', 'Basic', '2025-02-28', '2:51 PM', 99, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (468, 'Lester', 'Basic', '2025-05-04', '10:30 AM', 108, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (469, 'Jesse', 'Basic', '2025-08-16', '9:43 AM', 72, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (470, 'Bobbee', 'Platinum', '2025-06-13', '1:07 PM', 111, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (471, 'Pia', 'Basic', '2025-08-26', '7:30 PM', 38, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (472, 'Jojo', 'Gold', '2025-01-13', '1:54 PM', 45, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (473, 'Marcos', 'Platinum', '2025-09-17', '5:25 PM', 67, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (474, 'Latrena', 'Gold', '2025-07-19', '2:31 PM', 108, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (475, 'Tabb', 'Platinum', '2025-05-16', '4:18 PM', 111, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (476, 'Pavia', 'Gold', '2025-05-29', '12:35 PM', 68, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (477, 'Amy', 'Gold', '2025-01-22', '2:20 PM', 55, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (478, 'Hank', 'Basic', '2025-08-16', '3:50 PM', 67, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (479, 'Tabitha', 'Platinum', '2025-06-25', '10:48 AM', 81, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (480, 'Dannye', 'Basic', '2025-01-02', '2:54 PM', 96, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (481, 'Joline', 'Basic', '2025-04-06', '7:12 PM', 100, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (482, 'Camile', 'Gold', '2025-11-14', '8:00 PM', 63, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (483, 'Janeen', 'Basic', '2025-11-28', '3:27 PM', 94, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (484, 'Curtice', 'Basic', '2025-05-22', '9:50 AM', 96, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (485, 'Dynah', 'Gold', '2025-07-13', '6:30 PM', 37, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (486, 'Torey', 'Gold', '2025-05-09', '10:00 AM', 99, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (487, 'Lonni', 'Gold', '2025-05-03', '2:35 PM', 113, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (488, 'Kesley', 'Basic', '2025-02-24', '6:56 PM', 94, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (489, 'Meriel', 'Gold', '2025-12-17', '8:01 PM', 119, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (490, 'Pete', 'Basic', '2025-07-01', '6:16 PM', 92, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (491, 'Engracia', 'Basic', '2025-04-14', '10:01 AM', 98, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (492, 'Francisco', 'Platinum', '2025-02-25', '9:16 PM', 74, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (493, 'Thorn', 'Platinum', '2025-06-17', '2:01 PM', 61, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (494, 'Prue', 'Gold', '2025-06-30', '8:39 PM', 32, 'Crossfit');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (495, 'Aurora', 'Platinum', '2025-11-09', '8:42 AM', 60, 'Pesas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (496, 'Bertine', 'Gold', '2025-07-15', '7:11 PM', 99, 'Piscina');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (497, 'Karia', 'Platinum', '2025-11-14', '3:13 PM', 39, 'Cardio');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (498, 'Hall', 'Basic', '2025-08-28', '6:43 PM', 76, 'Clases Colectivas');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (499, 'Darlene', 'Basic', '2025-11-15', '7:36 PM', 101, 'Sauna');
insert into datos (socio_id, nombre_socio, tipo_suscripcion, fecha_acceso, hora_entrada, duracion_minutos, zona_actividad) values (500, 'Marjy', 'Platinum', '2025-12-10', '12:26 PM', 111, 'Piscina');
